//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignetSSRProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public string Attendance1 { get; set; }
        public Nullable<decimal> HoursMissed { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Excused { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
