//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignetSSRProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoursWorked
    {
        public int HoursWorkedID { get; set; }
        public int EmployeeID { get; set; }
        public int JobID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> HoursWorkedRT { get; set; }
        public Nullable<decimal> HoursWorkedOT { get; set; }
        public Nullable<int> ItemNumber { get; set; }
        public Nullable<int> WageHistoryID { get; set; }
        public string JobDescription { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }
        public virtual WageHistory WageHistory { get; set; }
    }
}
