//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignetSSRProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISC567_SSRS_DatabaseEntities : DbContext
    {
        public ISC567_SSRS_DatabaseEntities()
            : base("name=ISC567_SSRS_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<HoursWorked> HoursWorkeds { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<MaterialsExpense> MaterialsExpenses { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
        public virtual DbSet<WageHistory> WageHistories { get; set; }
        public virtual DbSet<LoginAudit> LoginAudits { get; set; }
    }
}
